### ISSUE TITLE
Implement Circom wrapper

### ISSUE THREAD

**Issue by arnaucube** [privacy-scaling-explorations/folding-schemes#16]
Depends on #15 .

The objective of the Circom wrapper is:
- fits in the `Frontend` trait (from #15 )
- users can plug their Circom circuits into one of the available folding schemes that follow the [`FoldingScheme`](https://github.com/privacy-scaling-explorations/folding-schemes/blob/9ae046c4fc47e1715d6bb2291e8af138b8b836e7/src/lib.rs#L28) trait, where the `Circom-wrapper` that follows the `Frontend` trait returns the [witness](https://github.com/privacy-scaling-explorations/folding-schemes/blob/9ae046c4fc47e1715d6bb2291e8af138b8b836e7/src/folding/nova/mod.rs#L32), the [public inputs](https://github.com/privacy-scaling-explorations/folding-schemes/blob/9ae046c4fc47e1715d6bb2291e8af138b8b836e7/src/folding/nova/mod.rs#L15) and the [R1CS matrices](https://github.com/privacy-scaling-explorations/folding-schemes/blob/9ae046c4fc47e1715d6bb2291e8af138b8b836e7/src/ccs/r1cs.rs#L6) (or the [CCS](https://github.com/privacy-scaling-explorations/folding-schemes/blob/main/src/ccs/mod.rs#L15) ones).

Related repos that might be useful:
- https://github.com/nalinbhardwaj/Nova-Scotia
- https://github.com/arkworks-rs/circom-compat

**Comment by yugonsan** [comment]
Hello, I’m interested in this issue but I’m not sure what the frontend trait should be. So after issue #15 (frontend trait) has been completed, may I contribute to this issue?

I could get the R1CS matrices and calculate the witness vector from circom using nova-scotia. This is the snippet code that I tried out.
https://github.com/yugonsan/circom_parser/blob/d66e41799c9a2bd7421d13f213e688b4711b149a/src/main.rs#L187

**Comment by arnaucube** [comment]
That's awesome @yugonsan ^^
I'll be off (OOO) for the next 3 weeks, but (tagging them to include them in the conv) @CPerezz and @han0110 will work on the design of the `frontend` trait (#15), I would say that coordinating with them will be the best option.

**Comment by huitseeker** [comment]
We also have https://github.com/lurk-lab/circom-scotia 😆

**Comment by CPerezz** [comment]
> Hello, I’m interested in this issue but I’m not sure what the frontend trait should be. So after issue #15 (frontend trait) has been completed, may I contribute to this issue?

Definitely! The frontend is the latter of our planned efforts anyways, so feel free to give it a try on designing the trait if you see like doing so too.
The main idea is that we should be able to fit in different providers (circom (via nova-scotia or whatever it is), Noir, Plonkish etc...) and handle all of them under a single trait (frontend) so that we can bring them into the `FoldingScheme` trait later and fold them.

> 
> I could get the R1CS matrices and calculate the witness vector from circom using nova-scotia. This is the snippet code that I tried out. https://github.com/yugonsan/circom_parser/blob/d66e41799c9a2bd7421d13f213e688b4711b149a/src/main.rs#L187

Once the provider structure is done + the trait is defined, feel free to go for this. But as said, unless @han0110 wants to give it a shot now, this fronted effort is going to be the last one of our first milestone.

**Comment by yugonsan** [comment]
@CPerezz 
I'm glad to hear that! So I'll start working on the design of the frontend trait then. Thank you for the opportunity.

**Comment by arnaucube** [comment]
Closing this task, since it was completed by @yugonsan at #26 :smile_cat:
