### ISSUE TITLE
KZG and Groth16 solidity verifiers generator method

### ISSUE THREAD

**Issue by arnaucube** [privacy-scaling-explorations/folding-schemes#58]
Compatible with the proofs generated by https://github.com/arkworks-rs/poly-commit/blob/master/poly-commit/src/kzg10/mod.rs .

This is for the onchain (Ethereum's EVM) decider case, where the `CommittedInstance`'s commitments use KZG for the instances of the main Nova circuit (and Pedersen for the CycleFold circuit instances).

The idea is to end up having a library method that given a trustedsetup of the kzg outputs the solidity code that verifies the commitments.

An implementation of a KZG Solidity verifier (non arkworks compatible) can be found at https://github.com/weijiekoh/libkzg/blob/master/sol/KZGVerifier.sol

Note that this is not yet the CLI, this is a library method. The CLI will be done once the KZG & Groth16 verifier generators are ready, the issue to track the CLI task is https://github.com/privacy-scaling-explorations/folding-schemes/issues/57

**Comment by dmpierre** [comment]
Will be tackling this as discussed! Can I/you update the title to reflect that this is the actual solidity contract library and not the CLI generator? Also, let's start a workspace where we can have an another repo for hosting this?
